name: Coq CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: coq-community/docker-coq-action@v1
        with:
          opam_file: 'theories/cp-next.opam'
          coq_version: '8.16.1'
          before_install: |
            startGroup "Add opam repo"
              opam repo add coq-extra-dev https://coq.inria.fr/opam/extra-dev
            endGroup
            startGroup "Print opam config"
              opam config list; opam repo list; opam list
            endGroup
